version: '3.7'

services:
  psql:
    image: postgres
    container_name: 'postgra'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
