server:
  port: 8085

spring:
  application:
    name: vote-client
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql=true
    hibernate:
      ddl-auto: update

  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_Password:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
