server:
  port: 8082

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: get-tanks
          uri: lb://facade
          predicates:
            - Path=/tanki
            - Method=GET

  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/




